apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  name: streaming-app
spec:
  acceptedServiceBindings:
  - name: foo-broker
    types:
    - rabbitmq
  build:
    buildpacks: {}
    nonSecretEnv:
    - name: BP_JVM_VERSION
      value: "21"
    path: ../..
  ports:
  - name: main
    port: 8080
  replicas: 1
