#IF(#databaseType == 'postgres')
---
volumes:
  postgres:
    driver: local
services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_DB=development
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
#ELSE
---
volumes:
  mysql-volume:
    driver: local
services:
  mysql:
    image: mysql:8.1
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=development
      - MYSQL_USER=local_test
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      -   mysql-volume:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - '8081:8080'
#ENDIF
